// <auto-generated />
using System;
using GestionCapitalHumano.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionCapitalHumano.Migrations
{
    [DbContext(typeof(CapitalHumanoContext))]
    [Migration("20230812202828_V1_CambiosEnModelo")]
    partial class V1_CambiosEnModelo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionCapitalHumano.Models.Area", b =>
                {
                    b.Property<int>("IdArea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdArea"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdArea");

                    b.ToTable("Area", (string)null);
                });

            modelBuilder.Entity("GestionCapitalHumano.Models.Asistencia", b =>
                {
                    b.Property<int>("IdAsistencia")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("HoraEntrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraSalida")
                        .HasMaxLength(10)
                        .HasColumnType("datetime2")
                        .IsFixedLength();

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.HasKey("IdAsistencia")
                        .HasName("PK_tabla1");

                    b.HasIndex("IdEmpleado");

                    b.ToTable("Asistencia");
                });

            modelBuilder.Entity("GestionCapitalHumano.Models.Capacitacion", b =>
                {
                    b.Property<int>("IdCapacitacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCapacitacion"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DuracionHoras")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.HasKey("IdCapacitacion");

                    b.ToTable("Capacitacion", (string)null);
                });

            modelBuilder.Entity("GestionCapitalHumano.Models.Contrato", b =>
                {
                    b.Property<int>("IdContrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContrato"));

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<string>("Seniority")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<decimal>("Sueldo")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("IdContrato");

                    b.ToTable("Contrato", (string)null);
                });

            modelBuilder.Entity("GestionCapitalHumano.Models.Departamento", b =>
                {
                    b.Property<int>("IdDepartamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDepartamento"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdArea")
                        .HasColumnType("int");

                    b.HasKey("IdDepartamento");

                    b.ToTable("Departamento", (string)null);
                });

            modelBuilder.Entity("GestionCapitalHumano.Models.Empleado", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpleado"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<int>("ContratoIdContrato")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("EquipoTrabajoIdEquipoTrabajo")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime");

                    b.Property<int>("Legajo")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ObraSocialIdObraSocial")
                        .HasColumnType("int");

                    b.Property<int>("PuestoTrabajoIdPuestoTrabajo")
                        .HasColumnType("int");

                    b.Property<int>("SindicatoIdSindicato")
                        .HasColumnType("int");

                    b.HasKey("IdEmpleado")
                        .HasName("PK_Empleados");

                    b.HasIndex("ContratoIdContrato");

                    b.HasIndex("EquipoTrabajoIdEquipoTrabajo");

                    b.HasIndex("ObraSocialIdObraSocial");

                    b.HasIndex("PuestoTrabajoIdPuestoTrabajo");

                    b.HasIndex("SindicatoIdSindicato");

                    b.ToTable("Empleado", (string)null);
                });

            modelBuilder.Entity("GestionCapitalHumano.Models.EmpleadoCapacitacion", b =>
                {
                    b.Property<int>("IdEmpleadoCapacitacion")
                        .HasColumnType("int")
                        .HasColumnName("IdEmpleado_Capacitacion");

                    b.Property<int>("IdCapacitacion")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.HasKey("IdEmpleadoCapacitacion");

                    b.HasIndex("IdCapacitacion");

                    b.HasIndex("IdEmpleado");

                    b.ToTable("Empleado_Capacitacion", (string)null);
                });

            modelBuilder.Entity("GestionCapitalHumano.Models.EmpleadoHabilidad", b =>
                {
                    b.Property<int>("IdEmpleadoHabilidad")
                        .HasColumnType("int")
                        .HasColumnName("IdEmpleado_Habilidad");

                    b.Property<int?>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int?>("IdHabilidad")
                        .HasColumnType("int");

                    b.HasKey("IdEmpleadoHabilidad")
                        .HasName("PK_dawdawd");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdHabilidad");

                    b.ToTable("Empleado_Habilidad", (string)null);
                });

            modelBuilder.Entity("GestionCapitalHumano.Models.EquipoTrabajo", b =>
                {
                    b.Property<int>("IdEquipoTrabajo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEquipoTrabajo"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("IdDepartamento")
                        .HasColumnType("int");

                    b.HasKey("IdEquipoTrabajo");

                    b.ToTable("EquipoTrabajo", (string)null);
                });

            modelBuilder.Entity("GestionCapitalHumano.Models.Experiencia", b =>
                {
                    b.Property<int>("IdExperiencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdExperiencia"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeSpan?>("Duracion")
                        .HasColumnType("time");

                    b.Property<int?>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int?>("IdTipoExperiencia")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdExperiencia");

                    b.ToTable("Experiencia");
                });

            modelBuilder.Entity("GestionCapitalHumano.Models.Habilidad", b =>
                {
                    b.Property<int>("IdHabilidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHabilidad"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdHabilidad");

                    b.ToTable("Habilidad", (string)null);
                });

            modelBuilder.Entity("GestionCapitalHumano.Models.ObraSocial", b =>
                {
                    b.Property<int>("IdObraSocial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdObraSocial"));

                    b.Property<decimal?>("Aporte")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdObraSocial");

                    b.ToTable("ObraSocial", (string)null);
                });

            modelBuilder.Entity("GestionCapitalHumano.Models.PuestoTrabajo", b =>
                {
                    b.Property<int>("IdPuestoTrabajo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPuestoTrabajo"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdPuestoTrabajo");

                    b.ToTable("PuestoTrabajo", (string)null);
                });

            modelBuilder.Entity("GestionCapitalHumano.Models.Sindicato", b =>
                {
                    b.Property<int>("IdSindicato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSindicato"));

                    b.Property<decimal?>("Aporte")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdSindicato");

                    b.ToTable("Sindicato", (string)null);
                });

            modelBuilder.Entity("GestionCapitalHumano.Models.Tarea", b =>
                {
                    b.Property<int>("IdTarea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTarea"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("IdPuestoTrabajo")
                        .HasColumnType("int");

                    b.HasKey("IdTarea");

                    b.ToTable("Tarea", (string)null);
                });

            modelBuilder.Entity("GestionCapitalHumano.Models.TipoExperiencia", b =>
                {
                    b.Property<int>("IdTipoExperiencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoExperiencia"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdTipoExperiencia");

                    b.ToTable("TipoExperiencia");
                });

            modelBuilder.Entity("GestionCapitalHumano.Models.Asistencia", b =>
                {
                    b.HasOne("GestionCapitalHumano.Models.Empleado", "IdEmpleadoNavigation")
                        .WithMany("Asistencia")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Asistenci__IdEmp__5CD6CB2B");

                    b.Navigation("IdEmpleadoNavigation");
                });

            modelBuilder.Entity("GestionCapitalHumano.Models.Empleado", b =>
                {
                    b.HasOne("GestionCapitalHumano.Models.Contrato", "Contrato")
                        .WithMany()
                        .HasForeignKey("ContratoIdContrato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionCapitalHumano.Models.EquipoTrabajo", "EquipoTrabajo")
                        .WithMany()
                        .HasForeignKey("EquipoTrabajoIdEquipoTrabajo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionCapitalHumano.Models.ObraSocial", "ObraSocial")
                        .WithMany()
                        .HasForeignKey("ObraSocialIdObraSocial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionCapitalHumano.Models.PuestoTrabajo", "PuestoTrabajo")
                        .WithMany()
                        .HasForeignKey("PuestoTrabajoIdPuestoTrabajo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionCapitalHumano.Models.Sindicato", "Sindicato")
                        .WithMany()
                        .HasForeignKey("SindicatoIdSindicato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrato");

                    b.Navigation("EquipoTrabajo");

                    b.Navigation("ObraSocial");

                    b.Navigation("PuestoTrabajo");

                    b.Navigation("Sindicato");
                });

            modelBuilder.Entity("GestionCapitalHumano.Models.EmpleadoCapacitacion", b =>
                {
                    b.HasOne("GestionCapitalHumano.Models.Capacitacion", "IdCapacitacionNavigation")
                        .WithMany("EmpleadoCapacitaciones")
                        .HasForeignKey("IdCapacitacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Empleado_Capacitacion_Capacitacion");

                    b.HasOne("GestionCapitalHumano.Models.Empleado", "IdEmpleadoNavigation")
                        .WithMany("EmpleadoCapacitacions")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Empleado_Capacitacion_Empleado");

                    b.Navigation("IdCapacitacionNavigation");

                    b.Navigation("IdEmpleadoNavigation");
                });

            modelBuilder.Entity("GestionCapitalHumano.Models.EmpleadoHabilidad", b =>
                {
                    b.HasOne("GestionCapitalHumano.Models.Empleado", "IdEmpleadoNavigation")
                        .WithMany("EmpleadoHabilidads")
                        .HasForeignKey("IdEmpleado")
                        .HasConstraintName("FK_Empleado_Habilidad_Empleado");

                    b.HasOne("GestionCapitalHumano.Models.Habilidad", "IdHabilidadNavigation")
                        .WithMany("EmpleadoHabilidads")
                        .HasForeignKey("IdHabilidad")
                        .HasConstraintName("FK_Empleado_Habilidad_Habilidad");

                    b.Navigation("IdEmpleadoNavigation");

                    b.Navigation("IdHabilidadNavigation");
                });

            modelBuilder.Entity("GestionCapitalHumano.Models.Capacitacion", b =>
                {
                    b.Navigation("EmpleadoCapacitaciones");
                });

            modelBuilder.Entity("GestionCapitalHumano.Models.Empleado", b =>
                {
                    b.Navigation("Asistencia");

                    b.Navigation("EmpleadoCapacitacions");

                    b.Navigation("EmpleadoHabilidads");
                });

            modelBuilder.Entity("GestionCapitalHumano.Models.Habilidad", b =>
                {
                    b.Navigation("EmpleadoHabilidads");
                });
#pragma warning restore 612, 618
        }
    }
}
